-- MySQL Script generated by MySQL Workbench
-- Mon May  2 13:30:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Train_Management_System
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Train_Management_System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Train_Management_System` DEFAULT CHARACTER SET utf8 ;
USE `Train_Management_System` ;

-- -----------------------------------------------------
-- Table `Train_Management_System`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Train_Management_System`.`user` (
  `userID` CHAR(20) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `gender` CHAR(1) NULL,
  `birthdate` DATE NULL,
  `email` VARCHAR(50) NULL,
  `contactNo` CHAR(15) NULL,
  `password` VARCHAR(20) NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Management_System`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Train_Management_System`.`passenger` (
  `PNR` CHAR(20) NOT NULL,
  `userID` CHAR(20) NOT NULL,
  `reservation_status` VARCHAR(5) NULL,
  `seat_no` VARCHAR(10) NULL,
  PRIMARY KEY (`PNR`, `userID`),
  INDEX `fk_passenger_user_idx` (`userID` ASC),
  CONSTRAINT `fk_passenger_user`
    FOREIGN KEY (`userID`)
    REFERENCES `Train_Management_System`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Management_System`.`train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Train_Management_System`.`train` (
  `train_no` CHAR(10) NOT NULL,
  `train_name` VARCHAR(50) NULL,
  `startStation` VARCHAR(50) NULL,
  `lastStation` VARCHAR(50) NULL,
  PRIMARY KEY (`train_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Management_System`.`train_timing`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `Train_Management_System`.`train_timing` (
  `train_no` CHAR(10) NOT NULL,
  `journeyDate` DATE NOT NULL,
  INDEX `fk_train_taming_train1_idx` (`train_no` ASC),
  PRIMARY KEY (`journeyDate`, `train_no`),
  CONSTRAINT `fk_train_taming_train1`
    FOREIGN KEY (`train_no`)
    REFERENCES `Train_Management_System`.`train` (`train_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Management_System`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Train_Management_System`.`ticket` (
  `ticket_no` VARCHAR(20) NOT NULL,
  `PNR` CHAR(20) NOT NULL,
  `journeyDate` DATE NOT NULL,
  `train_no` CHAR(10) NOT NULL,
  `price` INT NULL,
  `bookingDateTime` DATETIME NULL,
  PRIMARY KEY (`ticket_no`, `PNR`, `journeyDate`, `train_no`),
  INDEX `fk_ticket_passenger1_idx` (`PNR` ASC) ,
  INDEX `fk_ticket_train_timing1_idx` (`journeyDate` ASC, `train_no` ASC) ,
  CONSTRAINT `fk_ticket_passenger1`
    FOREIGN KEY (`PNR`)
    REFERENCES `Train_Management_System`.`passenger` (`PNR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_train_timing1`
    FOREIGN KEY (`journeyDate` , `train_no`)
    REFERENCES `Train_Management_System`.`train_timing` (`journeyDate` , `train_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Management_System`.`train_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Train_Management_System`.`train_routes` (
  `route_no` CHAR(10) NOT NULL,
  `train_no` CHAR(10) NOT NULL,
  PRIMARY KEY (`route_no`, `train_no`),
  INDEX `fk_train_routes_train1_idx` (`train_no` ASC),
  CONSTRAINT `fk_train_routes_train1`
    FOREIGN KEY (`train_no`)
    REFERENCES `Train_Management_System`.`train` (`train_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Management_System`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Train_Management_System`.`station` (
  `route_no` CHAR(10) NOT NULL,
  `station_name` VARCHAR(50) NULL,
  `arrivalTime` TIME NULL,
  `departureTime` TIME NULL,
  PRIMARY KEY (`route_no`),
  INDEX `fk_station_train_routes1_idx` (`route_no` ASC),
  CONSTRAINT `fk_station_train_routes1`
    FOREIGN KEY (`route_no`)
    REFERENCES `Train_Management_System`.`train_routes` (`route_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Management_System`.`train_specifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Train_Management_System`.`train_specifications` (
  `train_no` CHAR(10) NOT NULL,
  `seat` INT NULL,
  PRIMARY KEY (`train_no`),
  CONSTRAINT `fk_train_specifications_train1`
    FOREIGN KEY (`train_no`)
    REFERENCES `Train_Management_System`.`train` (`train_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Management_System`.`train_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Train_Management_System`.`train_status` (
  `train_no` CHAR(10) NOT NULL,
  `journeyDate` DATE NOT NULL,
  `seat_availibility` INT NULL,
  PRIMARY KEY (`train_no`, `journeyDate`),
  CONSTRAINT `fk_train_status_train_timing1`
    FOREIGN KEY (`train_no` , `journeyDate`)
    REFERENCES `Train_Management_System`.`train_timing` (`train_no` , `journeyDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
